/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SorocabaRouteImport } from './routes/sorocaba'
import { Route as SobreRouteImport } from './routes/sobre'
import { Route as SaoPauloRouteImport } from './routes/sao-paulo'
import { Route as RecifeRouteImport } from './routes/recife'
import { Route as RadioRouteImport } from './routes/radio'
import { Route as PernambucoRouteImport } from './routes/pernambuco'
import { Route as ItarareRouteImport } from './routes/itarare'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SorocabaGaleriaRouteImport } from './routes/sorocaba_.galeria'
import { Route as SaoPauloGaleriaRouteImport } from './routes/sao-paulo_.galeria'
import { Route as RecifeGaleriaRouteImport } from './routes/recife_.galeria'
import { Route as PernambucoGaleriaRouteImport } from './routes/pernambuco_.galeria'
import { Route as ItarareGaleriaRouteImport } from './routes/itarare_.galeria'
import { Route as SorocabaGaleriaTrabalhoRouteImport } from './routes/sorocaba_.galeria.$trabalho'
import { Route as SaoPauloGaleriaTrabalhoRouteImport } from './routes/sao-paulo_.galeria.$trabalho'
import { Route as RecifeGaleriaTrabalhoRouteImport } from './routes/recife_.galeria.$trabalho'
import { Route as PernambucoGaleriaTrabalhoRouteImport } from './routes/pernambuco_.galeria.$trabalho'
import { Route as ItarareGaleriaTrabalhoRouteImport } from './routes/itarare_.galeria.$trabalho'

const SorocabaRoute = SorocabaRouteImport.update({
  id: '/sorocaba',
  path: '/sorocaba',
  getParentRoute: () => rootRouteImport,
} as any)
const SobreRoute = SobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => rootRouteImport,
} as any)
const SaoPauloRoute = SaoPauloRouteImport.update({
  id: '/sao-paulo',
  path: '/sao-paulo',
  getParentRoute: () => rootRouteImport,
} as any)
const RecifeRoute = RecifeRouteImport.update({
  id: '/recife',
  path: '/recife',
  getParentRoute: () => rootRouteImport,
} as any)
const RadioRoute = RadioRouteImport.update({
  id: '/radio',
  path: '/radio',
  getParentRoute: () => rootRouteImport,
} as any)
const PernambucoRoute = PernambucoRouteImport.update({
  id: '/pernambuco',
  path: '/pernambuco',
  getParentRoute: () => rootRouteImport,
} as any)
const ItarareRoute = ItarareRouteImport.update({
  id: '/itarare',
  path: '/itarare',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SorocabaGaleriaRoute = SorocabaGaleriaRouteImport.update({
  id: '/sorocaba_/galeria',
  path: '/sorocaba/galeria',
  getParentRoute: () => rootRouteImport,
} as any)
const SaoPauloGaleriaRoute = SaoPauloGaleriaRouteImport.update({
  id: '/sao-paulo_/galeria',
  path: '/sao-paulo/galeria',
  getParentRoute: () => rootRouteImport,
} as any)
const RecifeGaleriaRoute = RecifeGaleriaRouteImport.update({
  id: '/recife_/galeria',
  path: '/recife/galeria',
  getParentRoute: () => rootRouteImport,
} as any)
const PernambucoGaleriaRoute = PernambucoGaleriaRouteImport.update({
  id: '/pernambuco_/galeria',
  path: '/pernambuco/galeria',
  getParentRoute: () => rootRouteImport,
} as any)
const ItarareGaleriaRoute = ItarareGaleriaRouteImport.update({
  id: '/itarare_/galeria',
  path: '/itarare/galeria',
  getParentRoute: () => rootRouteImport,
} as any)
const SorocabaGaleriaTrabalhoRoute = SorocabaGaleriaTrabalhoRouteImport.update({
  id: '/$trabalho',
  path: '/$trabalho',
  getParentRoute: () => SorocabaGaleriaRoute,
} as any)
const SaoPauloGaleriaTrabalhoRoute = SaoPauloGaleriaTrabalhoRouteImport.update({
  id: '/$trabalho',
  path: '/$trabalho',
  getParentRoute: () => SaoPauloGaleriaRoute,
} as any)
const RecifeGaleriaTrabalhoRoute = RecifeGaleriaTrabalhoRouteImport.update({
  id: '/$trabalho',
  path: '/$trabalho',
  getParentRoute: () => RecifeGaleriaRoute,
} as any)
const PernambucoGaleriaTrabalhoRoute =
  PernambucoGaleriaTrabalhoRouteImport.update({
    id: '/$trabalho',
    path: '/$trabalho',
    getParentRoute: () => PernambucoGaleriaRoute,
  } as any)
const ItarareGaleriaTrabalhoRoute = ItarareGaleriaTrabalhoRouteImport.update({
  id: '/$trabalho',
  path: '/$trabalho',
  getParentRoute: () => ItarareGaleriaRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/faq': typeof FaqRoute
  '/itarare': typeof ItarareRoute
  '/pernambuco': typeof PernambucoRoute
  '/radio': typeof RadioRoute
  '/recife': typeof RecifeRoute
  '/sao-paulo': typeof SaoPauloRoute
  '/sobre': typeof SobreRoute
  '/sorocaba': typeof SorocabaRoute
  '/itarare/galeria': typeof ItarareGaleriaRouteWithChildren
  '/pernambuco/galeria': typeof PernambucoGaleriaRouteWithChildren
  '/recife/galeria': typeof RecifeGaleriaRouteWithChildren
  '/sao-paulo/galeria': typeof SaoPauloGaleriaRouteWithChildren
  '/sorocaba/galeria': typeof SorocabaGaleriaRouteWithChildren
  '/itarare/galeria/$trabalho': typeof ItarareGaleriaTrabalhoRoute
  '/pernambuco/galeria/$trabalho': typeof PernambucoGaleriaTrabalhoRoute
  '/recife/galeria/$trabalho': typeof RecifeGaleriaTrabalhoRoute
  '/sao-paulo/galeria/$trabalho': typeof SaoPauloGaleriaTrabalhoRoute
  '/sorocaba/galeria/$trabalho': typeof SorocabaGaleriaTrabalhoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/faq': typeof FaqRoute
  '/itarare': typeof ItarareRoute
  '/pernambuco': typeof PernambucoRoute
  '/radio': typeof RadioRoute
  '/recife': typeof RecifeRoute
  '/sao-paulo': typeof SaoPauloRoute
  '/sobre': typeof SobreRoute
  '/sorocaba': typeof SorocabaRoute
  '/itarare/galeria': typeof ItarareGaleriaRouteWithChildren
  '/pernambuco/galeria': typeof PernambucoGaleriaRouteWithChildren
  '/recife/galeria': typeof RecifeGaleriaRouteWithChildren
  '/sao-paulo/galeria': typeof SaoPauloGaleriaRouteWithChildren
  '/sorocaba/galeria': typeof SorocabaGaleriaRouteWithChildren
  '/itarare/galeria/$trabalho': typeof ItarareGaleriaTrabalhoRoute
  '/pernambuco/galeria/$trabalho': typeof PernambucoGaleriaTrabalhoRoute
  '/recife/galeria/$trabalho': typeof RecifeGaleriaTrabalhoRoute
  '/sao-paulo/galeria/$trabalho': typeof SaoPauloGaleriaTrabalhoRoute
  '/sorocaba/galeria/$trabalho': typeof SorocabaGaleriaTrabalhoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/faq': typeof FaqRoute
  '/itarare': typeof ItarareRoute
  '/pernambuco': typeof PernambucoRoute
  '/radio': typeof RadioRoute
  '/recife': typeof RecifeRoute
  '/sao-paulo': typeof SaoPauloRoute
  '/sobre': typeof SobreRoute
  '/sorocaba': typeof SorocabaRoute
  '/itarare_/galeria': typeof ItarareGaleriaRouteWithChildren
  '/pernambuco_/galeria': typeof PernambucoGaleriaRouteWithChildren
  '/recife_/galeria': typeof RecifeGaleriaRouteWithChildren
  '/sao-paulo_/galeria': typeof SaoPauloGaleriaRouteWithChildren
  '/sorocaba_/galeria': typeof SorocabaGaleriaRouteWithChildren
  '/itarare_/galeria/$trabalho': typeof ItarareGaleriaTrabalhoRoute
  '/pernambuco_/galeria/$trabalho': typeof PernambucoGaleriaTrabalhoRoute
  '/recife_/galeria/$trabalho': typeof RecifeGaleriaTrabalhoRoute
  '/sao-paulo_/galeria/$trabalho': typeof SaoPauloGaleriaTrabalhoRoute
  '/sorocaba_/galeria/$trabalho': typeof SorocabaGaleriaTrabalhoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/faq'
    | '/itarare'
    | '/pernambuco'
    | '/radio'
    | '/recife'
    | '/sao-paulo'
    | '/sobre'
    | '/sorocaba'
    | '/itarare/galeria'
    | '/pernambuco/galeria'
    | '/recife/galeria'
    | '/sao-paulo/galeria'
    | '/sorocaba/galeria'
    | '/itarare/galeria/$trabalho'
    | '/pernambuco/galeria/$trabalho'
    | '/recife/galeria/$trabalho'
    | '/sao-paulo/galeria/$trabalho'
    | '/sorocaba/galeria/$trabalho'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/faq'
    | '/itarare'
    | '/pernambuco'
    | '/radio'
    | '/recife'
    | '/sao-paulo'
    | '/sobre'
    | '/sorocaba'
    | '/itarare/galeria'
    | '/pernambuco/galeria'
    | '/recife/galeria'
    | '/sao-paulo/galeria'
    | '/sorocaba/galeria'
    | '/itarare/galeria/$trabalho'
    | '/pernambuco/galeria/$trabalho'
    | '/recife/galeria/$trabalho'
    | '/sao-paulo/galeria/$trabalho'
    | '/sorocaba/galeria/$trabalho'
  id:
    | '__root__'
    | '/'
    | '/faq'
    | '/itarare'
    | '/pernambuco'
    | '/radio'
    | '/recife'
    | '/sao-paulo'
    | '/sobre'
    | '/sorocaba'
    | '/itarare_/galeria'
    | '/pernambuco_/galeria'
    | '/recife_/galeria'
    | '/sao-paulo_/galeria'
    | '/sorocaba_/galeria'
    | '/itarare_/galeria/$trabalho'
    | '/pernambuco_/galeria/$trabalho'
    | '/recife_/galeria/$trabalho'
    | '/sao-paulo_/galeria/$trabalho'
    | '/sorocaba_/galeria/$trabalho'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FaqRoute: typeof FaqRoute
  ItarareRoute: typeof ItarareRoute
  PernambucoRoute: typeof PernambucoRoute
  RadioRoute: typeof RadioRoute
  RecifeRoute: typeof RecifeRoute
  SaoPauloRoute: typeof SaoPauloRoute
  SobreRoute: typeof SobreRoute
  SorocabaRoute: typeof SorocabaRoute
  ItarareGaleriaRoute: typeof ItarareGaleriaRouteWithChildren
  PernambucoGaleriaRoute: typeof PernambucoGaleriaRouteWithChildren
  RecifeGaleriaRoute: typeof RecifeGaleriaRouteWithChildren
  SaoPauloGaleriaRoute: typeof SaoPauloGaleriaRouteWithChildren
  SorocabaGaleriaRoute: typeof SorocabaGaleriaRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sorocaba': {
      id: '/sorocaba'
      path: '/sorocaba'
      fullPath: '/sorocaba'
      preLoaderRoute: typeof SorocabaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sobre': {
      id: '/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof SobreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sao-paulo': {
      id: '/sao-paulo'
      path: '/sao-paulo'
      fullPath: '/sao-paulo'
      preLoaderRoute: typeof SaoPauloRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recife': {
      id: '/recife'
      path: '/recife'
      fullPath: '/recife'
      preLoaderRoute: typeof RecifeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/radio': {
      id: '/radio'
      path: '/radio'
      fullPath: '/radio'
      preLoaderRoute: typeof RadioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pernambuco': {
      id: '/pernambuco'
      path: '/pernambuco'
      fullPath: '/pernambuco'
      preLoaderRoute: typeof PernambucoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/itarare': {
      id: '/itarare'
      path: '/itarare'
      fullPath: '/itarare'
      preLoaderRoute: typeof ItarareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sorocaba_/galeria': {
      id: '/sorocaba_/galeria'
      path: '/sorocaba/galeria'
      fullPath: '/sorocaba/galeria'
      preLoaderRoute: typeof SorocabaGaleriaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sao-paulo_/galeria': {
      id: '/sao-paulo_/galeria'
      path: '/sao-paulo/galeria'
      fullPath: '/sao-paulo/galeria'
      preLoaderRoute: typeof SaoPauloGaleriaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recife_/galeria': {
      id: '/recife_/galeria'
      path: '/recife/galeria'
      fullPath: '/recife/galeria'
      preLoaderRoute: typeof RecifeGaleriaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pernambuco_/galeria': {
      id: '/pernambuco_/galeria'
      path: '/pernambuco/galeria'
      fullPath: '/pernambuco/galeria'
      preLoaderRoute: typeof PernambucoGaleriaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/itarare_/galeria': {
      id: '/itarare_/galeria'
      path: '/itarare/galeria'
      fullPath: '/itarare/galeria'
      preLoaderRoute: typeof ItarareGaleriaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sorocaba_/galeria/$trabalho': {
      id: '/sorocaba_/galeria/$trabalho'
      path: '/$trabalho'
      fullPath: '/sorocaba/galeria/$trabalho'
      preLoaderRoute: typeof SorocabaGaleriaTrabalhoRouteImport
      parentRoute: typeof SorocabaGaleriaRoute
    }
    '/sao-paulo_/galeria/$trabalho': {
      id: '/sao-paulo_/galeria/$trabalho'
      path: '/$trabalho'
      fullPath: '/sao-paulo/galeria/$trabalho'
      preLoaderRoute: typeof SaoPauloGaleriaTrabalhoRouteImport
      parentRoute: typeof SaoPauloGaleriaRoute
    }
    '/recife_/galeria/$trabalho': {
      id: '/recife_/galeria/$trabalho'
      path: '/$trabalho'
      fullPath: '/recife/galeria/$trabalho'
      preLoaderRoute: typeof RecifeGaleriaTrabalhoRouteImport
      parentRoute: typeof RecifeGaleriaRoute
    }
    '/pernambuco_/galeria/$trabalho': {
      id: '/pernambuco_/galeria/$trabalho'
      path: '/$trabalho'
      fullPath: '/pernambuco/galeria/$trabalho'
      preLoaderRoute: typeof PernambucoGaleriaTrabalhoRouteImport
      parentRoute: typeof PernambucoGaleriaRoute
    }
    '/itarare_/galeria/$trabalho': {
      id: '/itarare_/galeria/$trabalho'
      path: '/$trabalho'
      fullPath: '/itarare/galeria/$trabalho'
      preLoaderRoute: typeof ItarareGaleriaTrabalhoRouteImport
      parentRoute: typeof ItarareGaleriaRoute
    }
  }
}

interface ItarareGaleriaRouteChildren {
  ItarareGaleriaTrabalhoRoute: typeof ItarareGaleriaTrabalhoRoute
}

const ItarareGaleriaRouteChildren: ItarareGaleriaRouteChildren = {
  ItarareGaleriaTrabalhoRoute: ItarareGaleriaTrabalhoRoute,
}

const ItarareGaleriaRouteWithChildren = ItarareGaleriaRoute._addFileChildren(
  ItarareGaleriaRouteChildren,
)

interface PernambucoGaleriaRouteChildren {
  PernambucoGaleriaTrabalhoRoute: typeof PernambucoGaleriaTrabalhoRoute
}

const PernambucoGaleriaRouteChildren: PernambucoGaleriaRouteChildren = {
  PernambucoGaleriaTrabalhoRoute: PernambucoGaleriaTrabalhoRoute,
}

const PernambucoGaleriaRouteWithChildren =
  PernambucoGaleriaRoute._addFileChildren(PernambucoGaleriaRouteChildren)

interface RecifeGaleriaRouteChildren {
  RecifeGaleriaTrabalhoRoute: typeof RecifeGaleriaTrabalhoRoute
}

const RecifeGaleriaRouteChildren: RecifeGaleriaRouteChildren = {
  RecifeGaleriaTrabalhoRoute: RecifeGaleriaTrabalhoRoute,
}

const RecifeGaleriaRouteWithChildren = RecifeGaleriaRoute._addFileChildren(
  RecifeGaleriaRouteChildren,
)

interface SaoPauloGaleriaRouteChildren {
  SaoPauloGaleriaTrabalhoRoute: typeof SaoPauloGaleriaTrabalhoRoute
}

const SaoPauloGaleriaRouteChildren: SaoPauloGaleriaRouteChildren = {
  SaoPauloGaleriaTrabalhoRoute: SaoPauloGaleriaTrabalhoRoute,
}

const SaoPauloGaleriaRouteWithChildren = SaoPauloGaleriaRoute._addFileChildren(
  SaoPauloGaleriaRouteChildren,
)

interface SorocabaGaleriaRouteChildren {
  SorocabaGaleriaTrabalhoRoute: typeof SorocabaGaleriaTrabalhoRoute
}

const SorocabaGaleriaRouteChildren: SorocabaGaleriaRouteChildren = {
  SorocabaGaleriaTrabalhoRoute: SorocabaGaleriaTrabalhoRoute,
}

const SorocabaGaleriaRouteWithChildren = SorocabaGaleriaRoute._addFileChildren(
  SorocabaGaleriaRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FaqRoute: FaqRoute,
  ItarareRoute: ItarareRoute,
  PernambucoRoute: PernambucoRoute,
  RadioRoute: RadioRoute,
  RecifeRoute: RecifeRoute,
  SaoPauloRoute: SaoPauloRoute,
  SobreRoute: SobreRoute,
  SorocabaRoute: SorocabaRoute,
  ItarareGaleriaRoute: ItarareGaleriaRouteWithChildren,
  PernambucoGaleriaRoute: PernambucoGaleriaRouteWithChildren,
  RecifeGaleriaRoute: RecifeGaleriaRouteWithChildren,
  SaoPauloGaleriaRoute: SaoPauloGaleriaRouteWithChildren,
  SorocabaGaleriaRoute: SorocabaGaleriaRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
